### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tjdurden** [Alfresco/community-edition#3]
https://github.com/Alfresco/community-edition/blob/e0c6c4088320113db82e16ca5e3261aa321ec26d/projects/repository/source/java/org/alfresco/repo/mail/AlfrescoJavaMailSender.java#L215

**Comment by esplinr** [comment]
The GitHub issue tracker should not have been enabled because Alfresco uses a separate issue tracker. I moved this report here:

https://issues.alfresco.com/jira/browse/ALF-21310

Thanks for pointing this out.
